Online_Shop_App/article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='article_view'),
    path('cat/<str:catgory>', views.ArticlesListView.as_view(), name='article_cat_by_list'),
    path('<pk>/', views.ArticlesDetailView.as_view(), name='articles_detail'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment')
]

Online_Shop_App/eshop_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('user/', include('user_panel_module.urls')),
    path('order/', include('order_module.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Online_Shop_App/home_module/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.IndexView.as_view(), name="index_page"),
    path('about-us',views.AboutView.as_view(), name="about_us")
    # path('contact-us', views.contact_page),
    # path('site-header', views.site_header_component,)
]

Online_Shop_App/article_module/models.py
from django.db import models
from jalali_date import date2jalali
from account_module.models import User


class ArticleCat(models.Model):
    parent = models.ForeignKey('ArticleCat', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCat, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر', null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

Online_Shop_App/article_module/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from article_module.models import Article, ArticleCat, ArticleComment


class ArticlesListView(ListView):
    model = Article
    paginate_by = 4
    template_name = 'article_module/articel_page.html'

    def get_context_data(self, *args, object_list=None, **kwargs, ):
        context = super(ArticlesListView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        query = super(ArticlesListView, self).get_queryset()
        query = query.filter(is_active=True)
        catgory_name = self.kwargs.get('catgory')
        if catgory_name is not None:
            query = query.filter(selected_catgory__url_title__iexact=catgory_name)
        return query


class ArticlesDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_queryset(self):
        query = super(ArticlesDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticlesDetailView, self).get_context_data()
        article: Article = kwargs.get('object')  # kwargs is a dict
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent_id=None).order_by(
            'create_date').prefetch_related(
            'article__articlecomment_set')
        return context


def articel_catgories_partial(request: HttpRequest):
    articel_main = ArticleCat.objects.prefetch_related('articlecat_set').filter(is_active=True, parent=None)
    context = {
        'main_catgories': articel_main
    }
    return render(request, 'components/articel_catgories_components.html', context)


def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated :
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        print(article_id, article_comment, parent_id)
        new_comment = ArticleComment(article_id=article_id, text=article_comment, user_id=request.user.id,
                                      parent_id=parent_id)
        new_comment.save()
    return HttpResponse('response')

Online_Shop_App/article_module/templates/article_module/articel_page.html
{% extends 'shared/layout.html' %}
{% load thumbnail %}
{% load poll_axtras %}
{% load render_partial %}

{% block title %}مقاله های سایت  {% endblock %}

{% block content %}
    <section>
		<div class="container">
			<div class="row">

				<div class="col-sm-9">
					<div class="blog-post-area">
						<h2 class="title text-center">آخریـن اخبـار</h2>

                        {% for article in object_list %}
                            <div class="single-blog-post">
							<h3>{{ article.title }}</h3>
							<div class="post-meta">
								<ul>
									{% if article.author is not None %}
                                        <li><i class="fa fa-user"></i> {{ article.author.get_full_name }}</li>
									{% endif %}
									<li><i class="fa fa-clock-o"></i>{{ article.get_jalali_create_time }}</li>
									<li><i class="fa fa-calendar"></i> {{ article.create_date | show_jalali_date }} </li>
								</ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
							</div>
							<a href="">
                            {#<img src="{{ articel.image.url }}" alt="">#}
                                {% thumbnail article.image "900x850" quality=95 crop='center' as im %}
                                    <img src="{{ im.url }}" alt="">
                                {% endthumbnail %}
                            </a>

							<p>{{ article.short_description }}</p>
							<a class="btn btn-primary" href="{% url 'articles_detail' pk=article.pk%}">ادامه مطلب </a>
						    </div>
                        {% endfor %}



                        <ul class="pagination">
                                {% comment %}<li class="active"><a href="">1</a></li>
                                <li><a href="">2</a></li>
                                <li><a href="">3</a></li>
                                <li><a href="">»</a></li>{% endcomment %}
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    <li class="{% if page_obj.number == page %} active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
					</div>
				</div>

				<div class="col-sm-3">
					<div class="left-sidebar">
                            {% render_partial 'article_module.views.articel_catgories_partial'  %}
                        <div class="brands_products"><!--brands_products-->
							<h2>برنـد ها</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
									<li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
									<li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
									<li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
									<li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->



						<div class="shipping text-center"><!--shipping-->
							<img src="/static/images/home/shipping.jpg" alt="">
						</div><!--/shipping-->

					</div>
				</div>

			</div>
		</div>
	</section>




{% endblock %}

Online_Shop_App/article_module/templates/article_module/article_detail_page.html
{% extends 'shared/layout.html' %}
{% load thumbnail %}
{% load render_partial %}
{% load poll_axtras %}




{% block title %}
    جزییات مقالات
{% endblock %}

{% block content %}

    <section>
    <div class="container">
        <div class="row">

            <div class="col-sm-9">
                <div class="blog-post-area">
                    <h2 class="title text-center">{{ article.title }}</h2>
                    <div class="single-blog-post">
                        <h3>{{ article.title }}</h3>
                        <div class="post-meta">
                            <ul>
                                {% if articel.author is not None %}
                                    <li><i class="fa fa-user"></i> {{ article.author.get_full_name }}</li>
                                {% endif %}
                                <li><i class="fa fa-clock-o"></i>{{ article.get_jalali_create_time }}</li>
                                <li><i class="fa fa-calendar"></i> {{ article.create_date | show_jalali_date }} </li>
                            </ul>
                            <span>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                    <i class="fa fa-star-half-o"></i>
                            </span>
                        </div>
                        <a href="">
                         {% thumbnail article.image "900x850" quality=95 crop='center' as im %}
                             <img src="{{ im.url }}" alt="">
                         {% endthumbnail %}
                        </a>
                       <p>
                           {{ article.short_description }}
                       </p>
                        <p>
                           {{ article.text }}
                       </p>

                    </div>
                </div><!--/blog-post-area-->


                {% if article.author %}
                <div class="media commnets">
                    <a class="pull-right" href="#">
                       {% if article.author.avatar %}
                           {% thumbnail articel.author.avatar "121x86" quality=95 crop='center' as im %}
                                <img class="media-object" src="{{ im.url }}" alt="">
                            {% endthumbnail %}
                       {% else %}
                           <img class="media-object" src="/static/images/blog/Customer.jpg " alt=''>
                       {% endif %}
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">نویسنده : {{ article.author }}</h4>
                            <p>
                                {{ article.author.about_user }}
                            </p>
                    </div>
                </div>
                {% endif %}

<!--Comments-->
                    <div class="response-area" id="comments_area">
                        <h2> نظرات ({{ comments_count }})</h2>
                        <ul class="media-list">
                            {% for comment in comments %}
                                <li class="media" id="single_comment_box_{{ comment.id }}">
                                    <a class="pull-right" href="#">
                                        <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                    </a>
                                    <div class="media-body">
                                        <ul class="sinlge-post-meta">
                                            <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                            <li><i class="fa fa-clock-o"></i> {{ comment.create_date | time }}</li>
                                            <li>
                                                <i class="fa fa-calendar"></i> {{ comment.create_date|show_jalali_date }}
                                            </li>
                                        </ul>
                                        <p>
                                            {{ comment.text }}
                                        </p>
                                      {% comment %}  <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                                class="fa fa-reply"></i>پاسـخ</a>{% endcomment %}
                                    </div>
                                </li>

                                {% for sub_comment in comment.articlecomment_set.all %}
                                    <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                                        <a class="pull-right" href="#">
                                            <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                <li><i class="fa fa-clock-o"></i> {{ sub_comment.create_date | time }}
                                                </li>
                                                <li>
                                                    <i class="fa fa-calendar"></i> {{ sub_comment.create_date|show_jalali_date }}
                                                </li>
                                            </ul>
                                            <p>
                                                {{ sub_comment.text }}
                                            </p>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endfor %}

                        </ul>
                    </div><!--/Response-area-->
                    <div class="replay-box" id="comment_form">
                        {% if request.user.is_authenticated %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <h2>نظـر خود را بنویسیـد</h2>
                                    <div class="text-area">
                                        <input type="hidden" id="parent_id" value="">
                                        <div class="blank-arrow">
                                            <label>متن پیام</label>
                                        </div>
                                        <span>*</span>
                                        <label for="commentText"></label><textarea name="message" rows="11" id="commentText"></textarea>
                                        <a class="btn btn-primary" onclick="sendArticleComment({{ article.id }})">ارسـال
                                            نظـر</a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="alert alert-warning">
                                برای درج نظر می بایست <a href="{% url 'login_page' %}">لاگین</a> کنید
                            </div>
                        {% endif %}
                    </div><!--/Repaly Box-->
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'article_module.views.articel_catgories_partial' %}
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}