Online_Shop_App/eshop_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('user/', include('user_panel_module.urls')),
    path('order/', include('order_module.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Online_Shop_App/home_module/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.IndexView.as_view(), name="index_page"),
    path('about-us',views.AboutView.as_view(), name="about_us")
    # path('contact-us', views.contact_page),
    # path('site-header', views.site_header_component,)
]

Online_Shop_App/site_module/models.py
from django.db import models


# Create your models here.

class site_setting(models.Model):
    site_name = models.CharField(max_length=200, verbose_name="نام سایت")
    address = models.CharField(max_length=200, verbose_name="آدرس ")
    phone = models.CharField(max_length=200, null=True, blank=True, verbose_name="تلفن ")
    fax = models.CharField(max_length=200, null=True, blank=True, verbose_name="فکس ")
    email = models.CharField(max_length=200, null=True, blank=True, verbose_name="ایمیل ")
    copy_right = models.TextField(verbose_name="متن کپی رایت")
    logo = models.ImageField(upload_to='images/site-setting', verbose_name="لوگو سایت")
    site_url = models.CharField(max_length=200, verbose_name="دامنه سایت")
    about_us_text = models.TextField(verbose_name="درباره ی ما")
    is_main_setting = models.BooleanField(verbose_name="تنظیمات اصلی ")

    class Meta:
        verbose_name = "تنظیمات سایت"
        verbose_name_plural = "تنظیمات"

    def __str__(self):
        return self.site_name


class FooterLinkBox(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')

    class Meta:
        verbose_name = 'دسته بندی لینک های فوتر'
        verbose_name_plural = 'دسته بندی های لینک های فوتر'

    def __str__(self):
        return self.title


class FooterLink(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url = models.URLField(max_length=500, verbose_name='لینک')
    footer_link_box = models.ForeignKey(to=FooterLinkBox, on_delete=models.CASCADE, verbose_name='دسته بندی')

    class Meta:
        verbose_name = 'لینک فوتر'
        verbose_name_plural = 'لینک های فوتر'

    def __str__(self):
        return self.title


class Slider(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    url = models.URLField(max_length=500, verbose_name='لینک')
    url_link = models.CharField(max_length=200, verbose_name='عنوان لینک')
    description = models.TextField(verbose_name='توضیحات اسلایدر')
    image = models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر')
    is_active = models.BooleanField(default=True, verbose_name='فعال/غیر فعال')

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدر ها'

    def __str__(self):
        return self.title


# site_banner_positions = [
#     ('product_list', 'صفحه محصولات لیست'),
#     ('product_detail','صفحه جزییات محصول')
# ]


class SiteBanner(models.Model):
    class SiteBannerPositions(models.TextChoices):
        product_list = 'product_list', 'صفحه لیست محصولات',
        product_detail = 'product_detail', 'صفحه ی جزییات محصولات',
        about_us = 'about_us', 'درباره ما'

    title = models.CharField(max_length=200, verbose_name='عنوان بنر')
    url = models.URLField(max_length=400, null=True, blank=True, verbose_name='آدرس بنر')
    image = models.ImageField(upload_to='uploads/images/banners', verbose_name='تصویر بنر')
    is_active = models.BooleanField(verbose_name='فعال / غیرفعال')
    position = models.CharField(max_length=200, choices=SiteBannerPositions.choices, verbose_name='جایگاه نمایشی')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'بنر تبلیغاتی'
        verbose_name_plural = 'بنرهای تبلیغاتی'

Online_Shop_App/templates/shared/footer-references.html
<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.scrollUp.min.js"></script>
<script src="/static/js/price-range.js"></script>
<script src="/static/js/jquery.prettyPhoto.js"></script>
<script src="/static/js/main.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="/static/js/custom.js"></script>

Online_Shop_App/templates/shared/header-references.html
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/prettyPhoto.css" rel="stylesheet">
    <link href="/static/css/price-range.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
	<link href="/static/css/main.css" rel="stylesheet">
	<link href="/static/css/responsive.css" rel="stylesheet">
    <link href="/static/css/custom.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="/static/js/html5shiv.js"></script>
    <script src="/static/js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/static/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">

Online_Shop_App/templates/shared/layout.html
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    {% include 'shared/header-references.html' %}
</head>
<body>
{% render_partial 'home_module.views.site_header_component' %}
{% block content %}{% endblock %}
{% render_partial 'home_module.views.site_footer_component' %}
{% include 'shared/footer-references.html' %}
</body>
</html>

Online_Shop_App/templates/shared/site-footer-component.html
<footer id="footer"><!--Footer-->
		<div class="footer-Before">
			<div class="container">
				<div class="block-news">
					<div class="row">
						<h3>با عضویت در خبـرنامه ما از تخفیفات ویـژه ما با خبـر شوید ... </h3>
						<div class="searchform newslatter">
							<input type="text" placeholder="آدرس ایمیـل شما ..."/>
							<button type="submit" class="btn btn-default">
								<i class="fa fa-arrow-circle-o-left"></i>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-3">
						<div class="address">
							<img src="/static/images/home/map.png" alt="" />
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="/static/images/home/map.png" alt="" />
						</div>
					</div>
					<div class="col-sm-6">
						<div class="companyinfo">
							<h2>{{ site_setting.site_name }}</h2>
							<h4>درباره ما :</h4>
							<p>{{ site_setting.about_us_text }}</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					{% for footer_link_box in footer_link_boxes %}
					    <div class="col-sm-3 pull-right">
						<div class="single-widget">
							<h2>{{ footer_link_box.title }}</h2>
							<ul class="nav nav-pills nav-stacked">
								{% for link in footer_link_box.footerlink_set.all %}
                                    <li><a href="{{ link.url }}">{{ link.title }}</a></li>
								{% endfor %}
								
							</ul>
						</div>
					</div>
					{% endfor %}
					
				</div>
			</div>
		</div>

		<div class="footer-bottom" style="direction: ltr !important;">
			<div class="container">
				<div class="row">
					<p class="pull-right">
                        {{ site_setting.copy_right }}
					</p>
				</div>
			</div>
		</div>

</footer><!--/Footer-->

{#this file for django render partial#}

Online_Shop_App/templates/shared/site_header_component.html
<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> 80 21 24 36 98+ </a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<!-- <div class="col-sm-4 header-middle-menu">
						<div class="shop-menu pull-left">
							<ul class="nav navbar-nav">
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> پرداخت</a></li>
							</ul>
						</div>
					</div> -->

					<div class="col-sm-4" style="text-align: left;">
						<div class="logo">
							<a href="index.html"><img src="{{ site_setting.logo.url }}" alt="Logo" style="text-align: center;" /></a>
						</div>
					</div>

					<div class="col-sm-8 header-middle-menu">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
                                {% if request.user.is_authenticated %}
                                    {% if request.user.is_superuser %}
{#                                        <li><a href="{% url 'admin' %}"><i class="fa fa-shopping-cart"></i> پنل ادمین</a></li>#}
                                    {% endif %} 
                                    <li><a href="{% url 'user_basket_page' %}"><i class="fa fa-shopping-cart"></i> سبد خرید</a></li>
                                    <li><a href="{% url 'user_panel_dashboard' %}"><i class="fa fa-user"></i> پنل کاربری</a></li>
                                    <li><a href="{% url 'logout_page' %}"><i class="fa fa-sign-out"></i> خروج</a></li>
                                    {% else %}
                                    <li><a href="{% url 'register_page' %}"><i class="fa fa-sign-in"></i> ثبت نام</a></li>
                                    <li><a href="{% url 'login_page' %}"><i class="fa fa-sign-in"></i> ورود</a></li>
                                {% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">

					<div class="col-sm-3">
						<div class="search_box pull-left">
							<input type="text" placeholder="جستـجو"/>
						</div>
					</div>

					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-right">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li>
                                    <a href="{% url 'index_page' %}" class="{% if request.resolver_match.url_name == 'index_page' %}active{% endif %}">خـانه</a>
                                </li>
								<li>
                                    <a href="{% url 'product_list' %}" class ={% if request.resolver_match.url_name == 'product_list' %} active{% endif %} >فروشگـاه</a>
                                </li>
								<li>
                                    <a href="{% url 'article_view' %}" class ={% if request.resolver_match.url_name == 'article_view' %} active{% endif %}>مقالات</a>
                                </li>
								<li>
                                    <a href="{% url 'about_us' %}" class ={% if request.resolver_match.url_name == 'about_us' %} active{% endif %}>درباره مـا</a>
                                </li>
								<li>
                                    <a href="{% url 'contact_us_page' %}" class ={% if request.resolver_match.url_name == 'contact_us_page' %} active{% endif %} >تماس با مـا</a>
                                </li>
							</ul>
						</div>
					</div>

				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

{#this file for django render partial#}